site_name: Engineering
site_url: https://engineering.rise8.us
nav:
  - Home: index.md
  - Practice Playbook: practice-playbook.md
  - Blog:
    - blog/sample.md
  - Company: https://rise8.us
theme:
  name: material
  logo: logo-rise8.svg
  favicon: https://rise8.us/images/favicons/cropped-rise8-favicon-32x32.png
  palette:
    primary: black
    accent: red
  features:
    - navigation.tabs
    - navigation.tabs.sticky
extra_css:
  - stylesheets/extra.css
#plugins:
#  - social
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.emoji



